// GENERATED by cedarclerk-web/tools/generate-design-tokens.mjs — do not edit by hand.
// Source of truth: cedarclerk-web/src/styles.scss. Regenerate after changing a token.
namespace CedarClerk.Core;

/// <summary>
/// The design tokens, as the server-rendered surfaces need them (T-101, ADR-071 principle 6).
///
/// The blog used to carry its own copy of the palette, which is why the contrast pass fixed the
/// app and left the blog a shade behind. There is one source now — the stylesheet — and this file
/// is generated from it.
/// </summary>
public static class DesignTokens
{
    public static readonly IReadOnlyDictionary<string, string> Light = new Dictionary<string, string>
    {
        ["bg"] = "#ECE9E2",
        ["canvas"] = "#E2DED4",
        ["surface"] = "#F7F5EF",
        ["sheet"] = "#FCFBF8",
        ["alt"] = "#EFECE4",
        ["border"] = "#DBD5C8",
        ["border-strong"] = "#857D6F",
        ["text"] = "#26231D",
        ["t2"] = "#686257",
        ["t3"] = "#847E72",
        ["accent"] = "#566842",
        ["danger"] = "#A84129",
        ["ok"] = "#386D46",
        ["warn"] = "#7B5E0E",
        ["shadow"] = "0 1px 3px rgba(40, 35, 25, .10)",
        ["asoft"] = "color-mix(in srgb, var(--accent) 13%, var(--surface))",
        ["abord"] = "color-mix(in srgb, var(--accent) 38%, var(--border))",
        ["font-sans"] = "-apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
        ["font-mono"] = "ui-monospace, Menlo, Consolas, monospace",
        ["font-serif"] = "ui-serif, Georgia, \"Iowan Old Style\", \"Source Serif Pro\", \"Times New Roman\", serif",
        ["fs-read"] = "var(--fs-17)",
        ["lh-read"] = "1.7",
        ["radius-sm"] = "6px",
        ["radius-md"] = "10px",
        ["radius-lg"] = "14px",
    };

    /// <summary>Only what the dark theme overrides; everything else is inherited from <see cref="Light"/>.</summary>
    public static readonly IReadOnlyDictionary<string, string> Dark = new Dictionary<string, string>
    {
        ["bg"] = "#1D1B17",
        ["canvas"] = "#171511",
        ["surface"] = "#25221B",
        ["sheet"] = "#2B2820",
        ["alt"] = "#2F2C23",
        ["border"] = "#3C382D",
        ["border-strong"] = "#7B7465",
        ["text"] = "#EAE6DB",
        ["t2"] = "#A69F8F",
        ["t3"] = "#8B8477",
        ["accent"] = "color-mix(in srgb, #5B6E46 55%, #E8F0E8 45%)",
        ["danger"] = "#E2745C",
        ["ok"] = "#82BB8C",
        ["warn"] = "#E3C35C",
        ["shadow"] = "0 1px 3px rgba(0, 0, 0, .45)",
    };

    /// <summary>The declarations of one theme, ready to drop inside a CSS rule.</summary>
    public static string Declarations(IReadOnlyDictionary<string, string> tokens) =>
        string.Join(" ", tokens.Select(t => $"--{t.Key}: {t.Value};"));
}
