// GENERATED by cedarclerk-web/tools/generate-design-tokens.mjs — do not edit by hand.
// Source of truth: cedarclerk-web/src/styles.scss. Regenerate after changing a token.
namespace CedarClerk.Core;

/// <summary>
/// The design tokens, as the server-rendered surfaces need them (T-101, ADR-071 principle 6).
///
/// The blog used to carry its own copy of the palette, which is why the contrast pass fixed the
/// app and left the blog a shade behind. There is one source now — the stylesheet — and this file
/// is generated from it.
/// </summary>
public static class DesignTokens
{
    public static readonly IReadOnlyDictionary<string, string> Light = new Dictionary<string, string>
    {
        ["bg"] = "#F3EDDE",
        ["canvas"] = "#E9E1CC",
        ["surface"] = "#F1EADA",
        ["sheet"] = "#FAF6EC",
        ["alt"] = "#F5F0E1",
        ["border"] = "#CDC1A8",
        ["border-strong"] = "#8A6F4C",
        ["text"] = "#2C251A",
        ["t2"] = "#5B513E",
        ["t3"] = "#8C7F66",
        ["accent"] = "#39543C",
        ["danger"] = "#9E3D27",
        ["ok"] = "#356842",
        ["warn"] = "#7A5520",
        ["wood-ink"] = "#3A2918",
        ["series-1"] = "#39543C",
        ["series-2"] = "#3E5A76",
        ["series-3"] = "#A8721F",
        ["series-4"] = "#6B7F4A",
        ["series-5"] = "#7A5288",
        ["series-6"] = "#1F7A6E",
        ["shadow"] = "0 1px 3px rgba(58, 38, 16, .14)",
        ["asoft"] = "color-mix(in srgb, var(--accent) 13%, var(--surface))",
        ["abord"] = "color-mix(in srgb, var(--accent) 38%, var(--border))",
        ["font-sans"] = "'Source Sans 3', -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, system-ui, sans-serif",
        ["font-mono"] = "ui-monospace, Menlo, Consolas, monospace",
        ["font-serif"] = "'Literata', Georgia, \"Iowan Old Style\", serif",
        ["fs-read"] = "17px",
        ["lh-read"] = "1.75",
        ["radius-sm"] = "4px",
        ["radius-md"] = "8px",
        ["radius-lg"] = "12px",
    };

    /// <summary>Only what the dark theme overrides; everything else is inherited from <see cref="Light"/>.</summary>
    public static readonly IReadOnlyDictionary<string, string> Dark = new Dictionary<string, string>
    {
        ["bg"] = "#2E2718",
        ["canvas"] = "#251F13",
        ["surface"] = "#D9CEAE",
        ["sheet"] = "#E6DCC2",
        ["alt"] = "#DFD4B6",
        ["border"] = "#BCA98A",
        ["border-strong"] = "#7E6440",
        ["text"] = "#241E13",
        ["t2"] = "#564C35",
        ["t3"] = "#7F7257",
        ["danger"] = "#85311E",
        ["ok"] = "#2D5738",
        ["warn"] = "#68491B",
        ["wood-ink"] = "#E3D3AE",
        ["series-3"] = "#97661C",
        ["series-4"] = "#647645",
        ["shadow"] = "0 1px 3px rgba(0, 0, 0, .4)",
        ["asoft"] = "color-mix(in srgb, var(--accent) 10%, var(--surface))",
    };

    /// <summary>The declarations of one theme, ready to drop inside a CSS rule.</summary>
    public static string Declarations(IReadOnlyDictionary<string, string> tokens) =>
        string.Join(" ", tokens.Select(t => $"--{t.Key}: {t.Value};"));
}
