using CedarClerk.Core;
using CedarClerk.Server.Modules.IndieDev;

namespace CedarClerk.Server.Modules.Agent;

/// <summary>
/// The desktop agent's whole API (ADR-117).
///
/// ## What this is, and what it is deliberately not
///
/// It reads the disk of the machine it runs on and hands back descriptions: a folder's contents, one
/// file's stats, one file's thumbnail as JPEG bytes. It has **no database, no Identity, no session
/// and no knowledge of projects or owners** — those live in the cloud, which is the only place data
/// is stored. The agent cannot write a file, delete one, or launch one.
///
/// ## Why it needs a lock of its own
///
/// The sidecar this replaces was an ordinary Cedar Clerk closed by Identity's cookie. An agent has no
/// Identity, so an unauthenticated loopback service that lists folders would be readable by every
/// other process on the machine — and by any page in any browser, since a browser can reach
/// 127.0.0.1. Hence two independent gates, both required on every request:
///
/// 1. **Bearer token**, 32 random bytes generated by the shell per launch (<see cref="Consts.General.AgentTokenCfg"/>).
/// 2. **Granted roots** — see <see cref="AgentGrants"/>. The token says "you are the shell"; the grant
///    says "and this is the folder the human picked".
///
/// The token check is deliberately constant-time: a timing oracle on a local secret is a small hole,
/// but it is a hole a loop can widen, and the fix is one call.
/// </summary>
public static class AgentEndpoints
{
    public record GrantRequest(string? Root);
    public record ScanRequest(string? Root);
    public record ThumbRequest(string? Path);
    public record StatRequest(string? Root, string? RelativePath);

    /// <summary>Whether this process is an agent rather than a Cedar Clerk installation.</summary>
    public static bool IsAgent(IConfiguration config) => config.IsOn(Consts.General.AgentModeCfg);

    public static void MapAgentEndpoints(this WebApplication app)
    {
        var expected = app.Configuration[Consts.General.AgentTokenCfg];
        var group = app.MapGroup("/agent");

        // One filter rather than a check per handler: a new endpoint added later is authenticated by
        // default instead of by remembering. An agent launched without a token refuses everything —
        // failing closed is the only safe direction for a service whose job is reading a disk.
        group.AddEndpointFilter(async (ctx, next) =>
        {
            if (string.IsNullOrEmpty(expected)) return Results.StatusCode(StatusCodes.Status503ServiceUnavailable);

            var header = ctx.HttpContext.Request.Headers.Authorization.ToString();
            const string scheme = "Bearer ";
            var presented = header.StartsWith(scheme, StringComparison.Ordinal) ? header[scheme.Length..] : "";
            if (!FixedTimeEquals(presented, expected)) return Results.Unauthorized();

            return await next(ctx);
        });

        // Readiness. The shell polls this instead of sleeping, exactly as it polled /api/health
        // before — and the version is what catches a shell sitting next to an agent from another
        // build, which is a real possibility since both ship inside one installer.
        group.MapGet("/health", () => Results.Ok(new { version = Consts.CurrentVersion, agent = true }));

        // Called by the shell's main process after the OS folder dialog. The renderer never reaches
        // this: it has no way to name a folder the human did not pick.
        group.MapPost("/grant", (GrantRequest? req, AgentGrants grants) =>
        {
            if (string.IsNullOrWhiteSpace(req?.Root)) return Results.BadRequest(new { error = "A folder is required." });

            string root;
            try
            {
                root = Path.GetFullPath(req.Root.Trim());
            }
            catch (Exception)
            {
                return Results.BadRequest(new { error = "That is not a usable path." });
            }

            if (!Directory.Exists(root)) return Results.BadRequest(new { error = "That folder does not exist." });

            grants.Grant(root);
            return Results.Ok(new { root });
        });

        group.MapPost("/scan", (ScanRequest? req, AgentGrants grants, AgentScanService scans) =>
        {
            if (string.IsNullOrWhiteSpace(req?.Root)) return Results.BadRequest(new { error = "A folder is required." });
            if (!grants.Allows(req.Root)) return Forbidden();
            if (!Directory.Exists(req.Root)) return Results.BadRequest(new { error = "That folder does not exist." });

            return Results.Ok(Describe(scans.Start(Path.GetFullPath(req.Root))));
        });

        group.MapGet("/scan/{id:guid}", (Guid id, AgentScanService scans) =>
            scans.Get(id) is { } scan ? Results.Ok(Describe(scan)) : Results.NotFound());

        group.MapGet("/scan/{id:guid}/files", (Guid id, AgentScanService scans, int skip = 0, int take = 500) =>
        {
            if (scans.Get(id) is not { } scan) return Results.NotFound();
            // Clamped, not trusted: an unbounded page over a hundred thousand rows is a response
            // that never finishes serialising.
            var files = scans.Page(scan, Math.Max(0, skip), Math.Clamp(take, 1, 1000));
            return Results.Ok(new { files, described = scan.Described, status = Status(scan), scan.Total });
        });

        group.MapDelete("/scan/{id:guid}", (Guid id, AgentScanService scans) =>
            scans.Cancel(id) ? Results.NoContent() : Results.NotFound());

        // Re-stat one file, for the "Re-index file" button. The agent answers what the disk says now;
        // the page decides what that means and tells the cloud.
        group.MapPost("/stat", (StatRequest? req, AgentGrants grants) =>
        {
            if (string.IsNullOrWhiteSpace(req?.Root) || string.IsNullOrWhiteSpace(req.RelativePath))
                return Results.BadRequest(new { error = "A folder and a file are required." });

            var full = Path.Combine(req.Root, req.RelativePath.Replace('/', Path.DirectorySeparatorChar));
            if (!grants.Allows(full)) return Forbidden();

            var described = AssetFolderWalker.Describe(Path.GetFullPath(req.Root), full);
            return described is null ? Results.Ok(new { missing = true }) : Results.Ok(new { missing = false, file = described });
        });

        // The thumbnail, as bytes. Rendered here because this is the only process that can see the
        // file: ImageSharp for ordinary formats, our own parser for a .blend's embedded preview.
        group.MapPost("/thumb", (ThumbRequest? req, AgentGrants grants, ILogger<AgentScanService> logger) =>
        {
            if (string.IsNullOrWhiteSpace(req?.Path)) return Results.BadRequest(new { error = "A file is required." });
            if (!grants.Allows(req.Path)) return Forbidden();
            if (!AssetMetadata.CanHaveThumbnail(req.Path)) return Results.NotFound();

            var jpeg = AssetMetadata.TryRenderThumbnail(req.Path, logger);
            return jpeg is null ? Results.NotFound() : Results.Bytes(jpeg, "image/jpeg");
        });
    }

    /// <summary>
    /// Named separately because the message is the point: a refusal here means the page asked for
    /// something outside the folder its human chose, which is a defect or an attack, never a typo.
    /// </summary>
    private static IResult Forbidden() =>
        Results.Json(new { error = "That path is outside the folder this session was given." },
            statusCode: StatusCodes.Status403Forbidden);

    private static object Describe(AgentScan scan) => new
    {
        scanId = scan.Id,
        status = Status(scan),
        running = scan.Status is AgentScanStatus.Counting or AgentScanStatus.Scanning,
        scan.RootPath,
        scan.Total,
        scan.Described,
        scan.Unreadable,
        scan.Error,
        scan.StartedAt,
        scan.FinishedAt,
    };

    private static string Status(AgentScan scan) => scan.Status.ToString().ToLowerInvariant();

    /// <summary>
    /// Constant-time comparison. <see cref="string.Equals(string?, string?)"/> returns on the first
    /// differing character, which leaks the length of a correct prefix to anything that can time it.
    /// </summary>
    private static bool FixedTimeEquals(string a, string b) =>
        System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(
            System.Text.Encoding.UTF8.GetBytes(a), System.Text.Encoding.UTF8.GetBytes(b));
}
