// GENERATED by tools/generate-icon-usage.mjs — do not edit by hand.
// Every app-icon call site in src/app, with the label its control carries (T-080).
// 91 distinct icons across 540 call sites.

export interface IconUsageRow {
    /** Icon name, or "(dynamic)" where the template binds [name] to an expression. */
    icon: string;
    count: number;
    /** The accessible names this icon appears under — a raw t() path, or literal text. */
    labels: string[];
    files: string[];
}

export const ICON_USAGE: IconUsageRow[] = [
    {
        "icon": "(dynamic)",
        "count": 64,
        "labels": [
            "a.fileName",
            "a.relativePath",
            "accessibleLabel()",
            "baseTypeName(type)",
            "blockTitle(block) blockLabel(block.kind)",
            "command.label",
            "command.label groupLabel(command.group) command.shortcut",
            "d.title || t().drafts.untitled projectName(d.projectId) · postActivity(d) d.blogPublishedAt | zonedDate:'d MMM' t().manager.unpublishedChip d.updatedAt | zonedDate:'d MMM' · l.toUpperCase() + extra t().manager.privateChip + n publishStateLabel(d)",
            "fullscreenLabel()",
            "group.label",
            "hit.title || t().drafts.untitled hit.snippet t().search.published",
            "item.label",
            "item.label count",
            "labels().themeLabel",
            "memberSortDirection() === 'asc' ? t().common.ascending : t().common.descending",
            "object.title object.detail",
            "op.task statusLabel(op.status) t().ai.changedCount(changedCount(op)) · t().ai.untouchedCount(untouchedCount(op)) · t().ai.creditsSpent(op.credits) · duration(op)",
            "p.name",
            "preset.name presetConfig(preset).headings.length ? presetConfig(preset).headings.join(' · ') : t().presets.kinds.document.emptyConfig t().presets.kinds.document.name",
            "projectTypeName(type)",
            "revealed() ? t().authLayout.hidePassword : t().authLayout.showPassword",
            "selectLabel()",
            "slot.isActive ? t().calendar.queue.pause : t().calendar.queue.resume",
            "t().editor.exportModal.sortName",
            "t().editor.exportModal.sortSize",
            "t().editor.exportModal.sortType",
            "t().editor.previewTab.toggleTheme",
            "t().projects.assets.notFoundAtPath t().projects.assets.previewPending t().projects.assets.noPreview(t().projects.assets.kindOne[a.kind]) t().projects.assets.fingerprint a.fileName detailsOf(a) · a.modifiedAt | zonedDate:'d MMM'",
            "t().projects.docTypes[type].name t().projects.docTypes[type].blurb isPublishableType(type) ? t().projects.newDoc.publishes : t().projects.newDoc.workingMaterial",
            "t().projects.openDocument",
            "t().shell.inspector.toggle",
            "teamSortDirection() === 'asc' ? t().common.ascending : t().common.descending",
            "ticket.status === 'Pending' ? t().calendar.rescheduleTicketTitle(ticket.title, ticket.time) : null",
            "wordFor(option.mode)"
        ],
        "files": [
            "bench/forms/input.component.ts",
            "bench/worktop/module-tile.component.ts",
            "bench/worktop/sort-header.component.ts",
            "pages/ai-operations.component.html",
            "pages/calendar.component.html",
            "pages/editor-preview/editor-preview.component.ts",
            "pages/editor-preview/preview-checks.component.ts",
            "pages/editor-preview/preview-phone.component.ts",
            "pages/editor-preview/state-tag.component.ts",
            "pages/editor-publish/destination-card.component.ts",
            "pages/editor.component.html",
            "pages/landing-editor.component.html",
            "pages/media-library.component.html",
            "pages/posts-manager.component.html",
            "pages/presets.component.html",
            "pages/project-assets.component.html",
            "pages/project-showcase.component.html",
            "pages/project-tasks.component.html",
            "pages/project.component.html",
            "pages/projects.component.html",
            "pages/teams.component.html",
            "shared/command-palette.component.html",
            "shared/document-outline.component.ts",
            "shared/media-picker.component.html",
            "shared/search-overlay.component.html",
            "shared/theme-menu.component.ts",
            "shell/app-shell.component.ts",
            "shell/document-frame.component.ts",
            "shell/empty-state.component.ts",
            "shell/inspector-rail.component.ts",
            "shell/menu-bar.component.ts",
            "shell/project-switcher.component.ts",
            "shell/sidebar.component.ts"
        ]
    },
    {
        "icon": "check",
        "count": 39,
        "labels": [
            "baseTypeName(type)",
            "command.label command.shortcut",
            "destinationName(d)",
            "i + 1 t().editor.publishTab.steps[step.id] · t().editor.publishTab.stepDone",
            "languageLabel(l)",
            "preset.name presetBlurb(preset) presetStarter(preset)",
            "projectTypeName(type)",
            "t().common.save",
            "t().common.saved t().editor.exportModal.ctaSave",
            "t().editor.exportModal.copied t().editor.exportModal.copyFor(target.name)",
            "t().editor.exportModal.copied t().editor.exportModal.trackedLinkCopy(l.toUpperCase())",
            "t().editor.exportModal.trackedLinkCustomCopy",
            "t().manager.forms.typeChoice",
            "t().manager.forms.typeConsent",
            "t().manager.forms.typeLongText",
            "t().manager.forms.typeMulti",
            "t().manager.forms.typeStatic",
            "t().manager.forms.typeText",
            "t().presets.project.documentTypeDefault(defaultProjectDocumentTypeName())",
            "t().settings.appearance.accentHint + ' — ' + preset.name",
            "ticket.status === 'Pending' ? t().calendar.rescheduleTicketTitle(ticket.title, ticket.time) : null"
        ],
        "files": [
            "pages/calendar.component.html",
            "pages/editor-publish/publish-stepper.component.ts",
            "pages/editor.component.html",
            "pages/forms.component.html",
            "pages/presets.component.html",
            "pages/projects.component.html",
            "pages/settings.component.html",
            "shared/appearance-panel.component.html",
            "shared/feedback-panel.component.ts",
            "shared/publish-matrix.component.ts",
            "shell/menu-bar.component.ts"
        ]
    },
    {
        "icon": "plus",
        "count": 39,
        "labels": [
            "doc.title",
            "t().drafts.folders.add",
            "t().drafts.series.add",
            "t().editor.exportModal.ctaAdd",
            "t().editor.exportModal.invite",
            "t().projects.create.addLogo",
            "t().projects.tasks.addHere",
            "t().stats.inviteLinks.create"
        ],
        "files": [
            "pages/calendar.component.html",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/forms.component.html",
            "pages/glossary.component.html",
            "pages/posts-manager.component.html",
            "pages/presets.component.html",
            "pages/project-assets.component.html",
            "pages/project-boards.component.html",
            "pages/project-builds.component.html",
            "pages/project-dialogue.component.html",
            "pages/project-dialogues.component.html",
            "pages/project-planner.component.html",
            "pages/project-showcase.component.html",
            "pages/project-tasks.component.html",
            "pages/project.component.html",
            "pages/projects.component.html",
            "pages/stats.component.html",
            "pages/teams.component.html",
            "shared/folder-picker.component.html",
            "shared/series-picker.component.html"
        ]
    },
    {
        "icon": "x",
        "count": 34,
        "labels": [
            "p.status === 'Pending' ? t().manager.cancelScheduled : t().manager.removeFromList",
            "removeLabel() || null",
            "t().common.cancel",
            "t().common.cancel · aiEditProgress() %",
            "t().common.close",
            "t().common.delete",
            "t().editor.exportModal.changeChannel",
            "t().editor.exportModal.ctaRemove",
            "t().editor.exportModal.detachAsset",
            "t().editor.exportModal.revoke",
            "t().editor.tableMenu.deleteColumn",
            "t().editor.tableMenu.deleteRow",
            "t().editor.tags.deleteEverywhere",
            "t().manager.forms.removeLang",
            "t().manager.forms.removeOption",
            "t().manager.forms.removeQuestion",
            "t().projects.assets.unlink",
            "t().projects.canvas.removeMember",
            "t().projects.create.removeBanner",
            "t().projects.create.removeLogo",
            "t().projects.tasks.removeFile",
            "t().projects.tasks.unlink",
            "t().stats.inviteLinks.revoke"
        ],
        "files": [
            "bench/display/leaf-tag.component.ts",
            "pages/editor.component.html",
            "pages/forms.component.html",
            "pages/media-library.component.html",
            "pages/posts-manager.component.html",
            "pages/project-assets.component.html",
            "pages/project-tasks.component.html",
            "pages/projects.component.html",
            "pages/stats.component.html",
            "shared/debug-console.component.html",
            "shared/folder-picker.component.html",
            "shared/glossary-term-form.component.html",
            "shared/modal.component.html",
            "shared/project-members-panel.component.html",
            "shared/publish-matrix.component.ts",
            "shared/series-picker.component.html",
            "shared/tag-picker.component.html"
        ]
    },
    {
        "icon": "arrow-clockwise",
        "count": 30,
        "labels": [
            "(busy spinner)",
            "auth.hasAiPlan() ? t().manager.forms.translateLang : t().planLock.pro",
            "t().editor.exportModal.resend",
            "t().editor.syncFailedRetry"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/forms.component.html",
            "pages/glossary.component.html",
            "pages/media-library.component.html",
            "pages/posts-manager.component.html",
            "pages/project-assets.component.html",
            "pages/settings.component.html",
            "shared/glossary-term-form.component.html",
            "shared/media-picker.component.html"
        ]
    },
    {
        "icon": "trash",
        "count": 28,
        "labels": [
            "t().calendar.queue.remove",
            "t().common.delete",
            "t().debug.clear",
            "t().drafts.actions.deleteDraft",
            "t().editor.lang.deleteTranslation",
            "t().editor.tableMenu.deleteTable",
            "t().feedback.deleteComment",
            "t().manager.forms.deleteSubmission",
            "t().projects.canvas.deleteBoard",
            "t().projects.canvas.deleteItems",
            "t().projects.dialogues.deleteScript",
            "t().projects.showcase.removeBlock"
        ],
        "files": [
            "pages/admin.component.html",
            "pages/ai-operations.component.html",
            "pages/calendar.component.html",
            "pages/comments.component.html",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/forms.component.html",
            "pages/glossary.component.html",
            "pages/posts-manager.component.html",
            "pages/presets.component.html",
            "pages/project-boards.component.html",
            "pages/project-canvas.component.html",
            "pages/project-dialogue.component.html",
            "pages/project-dialogues.component.html",
            "pages/project-showcase.component.html",
            "pages/teams.component.html",
            "shared/debug-console.component.html",
            "shared/folder-picker.component.html",
            "shared/series-picker.component.html",
            "shared/tag-picker.component.html"
        ]
    },
    {
        "icon": "info",
        "count": 21,
        "labels": [
            "selectedId() === d.id ? t().drafts.actions.stopDescribing : t().drafts.actions.describe",
            "t().common.about"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "shared/hint-dot.component.ts"
        ]
    },
    {
        "icon": "warning",
        "count": 18,
        "labels": [
            "t().projects.assets.notFoundAtPath t().projects.assets.previewPending t().projects.assets.noPreview(t().projects.assets.kindOne[a.kind]) t().projects.assets.fingerprint a.fileName detailsOf(a) · a.modifiedAt | zonedDate:'d MMM'"
        ],
        "files": [
            "pages/calendar.component.html",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/onboarding.component.html",
            "pages/project-assets.component.html",
            "pages/project-boards.component.html",
            "pages/project-dialogue.component.html",
            "pages/project-dialogues.component.html",
            "pages/project.component.html",
            "shared/confirmation-dialog.component.ts",
            "shared/project-members-panel.component.html"
        ]
    },
    {
        "icon": "link",
        "count": 14,
        "labels": [
            "t().editor.exportModal.copied t().editor.exportModal.trackedLinkCopy(l.toUpperCase())",
            "t().editor.exportModal.copyInvite",
            "t().editor.exportModal.trackedLinkCustomCopy",
            "t().editor.preview.shareTitle",
            "t().editor.tb.insert",
            "t().stats.inviteLinks.copy"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-assets.component.html",
            "pages/project-canvas.component.html",
            "pages/project-tasks.component.html",
            "pages/project.component.html",
            "pages/stats.component.html",
            "shared/project-members-panel.component.html"
        ]
    },
    {
        "icon": "caret-down",
        "count": 10,
        "labels": [
            "isCollapsed(group) ? t().projects.planner.expand : t().projects.planner.collapse",
            "isCollapsed(row.d.id) ? t().drafts.tree.expand : t().drafts.tree.collapse",
            "t().editor.tb.expandableQuote",
            "triggerTitle()",
            "variant() === 'compact' ? name() : null"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/project-planner.component.html",
            "shared/language-menu.component.ts",
            "shell/project-switcher.component.ts"
        ]
    },
    {
        "icon": "pencil-simple",
        "count": 10,
        "labels": [
            "t().common.edit",
            "t().drafts.folders.rename",
            "t().drafts.series.rename",
            "t().editor.tags.rename",
            "t().projects.builds.editBuild",
            "t().projects.canvas.renameBoard",
            "t().projects.dialogues.renameScript",
            "t().projects.planner.editSprint"
        ],
        "files": [
            "pages/glossary.component.html",
            "pages/presets.component.html",
            "pages/project-boards.component.html",
            "pages/project-builds.component.html",
            "pages/project-dialogues.component.html",
            "pages/project-planner.component.html",
            "shared/folder-picker.component.html",
            "shared/series-picker.component.html",
            "shared/tag-picker.component.html"
        ]
    },
    {
        "icon": "arrow-square-out",
        "count": 9,
        "labels": [
            "channelLabel(channel)",
            "displayUrl(link.href)",
            "displayUrl(url)",
            "linkOf(item).url",
            "t().manager.openBlog",
            "t().manager.openTelegram",
            "t().manager.threadOf(post.partCount) t().manager.openPost(networkLabel(post.network))",
            "t().projects.showcase.openPage"
        ],
        "files": [
            "pages/posts-manager.component.html",
            "pages/project-canvas.component.html",
            "pages/project-showcase.component.html",
            "pages/project.component.html"
        ]
    },
    {
        "icon": "download-simple",
        "count": 9,
        "labels": [
            "(busy spinner)",
            "t().editor.exportModal.downloadCedar",
            "t().editor.exportModal.downloadZip",
            "t().stats.exportCsvHint"
        ],
        "files": [
            "pages/download.component.html",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/project-assets.component.html",
            "pages/project-dialogue.component.html",
            "pages/project-showcase.component.html",
            "pages/stats.component.html"
        ]
    },
    {
        "icon": "lock",
        "count": 9,
        "labels": [
            "allLocked() ? t().projects.canvas.unlock : t().projects.canvas.lock",
            "d.title || t().drafts.untitled",
            "d.title || t().drafts.untitled projectName(d.projectId) · postActivity(d) d.blogPublishedAt | zonedDate:'d MMM' t().manager.unpublishedChip d.updatedAt | zonedDate:'d MMM' · l.toUpperCase() + extra t().manager.privateChip + n publishStateLabel(d)",
            "t().shell.inspector.protectedField",
            "title()"
        ],
        "files": [
            "pages/ai-operations.component.html",
            "pages/drafts.component.html",
            "pages/posts-manager.component.html",
            "pages/project-canvas.component.html",
            "shared/plan-lock.component.ts",
            "shell/inspector-rail.component.ts"
        ]
    },
    {
        "icon": "paper-plane-tilt",
        "count": 9,
        "labels": [
            "publishButtonLabel()",
            "t().projects.canvas.inviteResend",
            "t().teams.resend"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project.component.html",
            "pages/settings.component.html",
            "pages/teams.component.html",
            "shared/project-members-panel.component.html"
        ]
    },
    {
        "icon": "caret-right",
        "count": 8,
        "labels": [
            "periodForwardTitle()",
            "t().editor.frame.continueToPreview",
            "t().editor.frame.continueToPublish"
        ],
        "files": [
            "pages/calendar.component.html",
            "pages/editor-publish/publish-stepper.component.ts",
            "pages/editor.component.html",
            "pages/glossary.component.html",
            "pages/media-library.component.html",
            "pages/settings.component.html",
            "shared/media-picker.component.html"
        ]
    },
    {
        "icon": "image",
        "count": 8,
        "labels": [
            "t().editor.tb.image",
            "t().projects.create.addBanner"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-canvas.component.html",
            "pages/project-showcase.component.html",
            "pages/project.component.html",
            "pages/projects.component.html",
            "shared/glossary-term-form.component.html"
        ]
    },
    {
        "icon": "layout",
        "count": 8,
        "labels": [
            "d.isTemplate ? t().drafts.actions.unmarkTemplate : t().drafts.actions.markTemplate",
            "inspectorOpen() ? t().editor.frame.hideDetails : t().editor.frame.details",
            "t().shell.commands.toggleSidebar"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/project-canvas.component.html",
            "pages/project.component.html",
            "shell/app-shell.component.ts"
        ]
    },
    {
        "icon": "archive",
        "count": 7,
        "labels": [
            "(busy spinner)",
            "d.isArchived ? t().drafts.actions.unarchive : t().drafts.actions.archive",
            "t().editor.tb.library"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/posts-manager.component.html",
            "shared/media-picker.component.html"
        ]
    },
    {
        "icon": "clock",
        "count": 7,
        "labels": [
            "t().editor.inspector.history",
            "t().editor.tb.datetime",
            "t().shell.inspector.openHistory(operations.operations().length)"
        ],
        "files": [
            "pages/calendar.component.html",
            "pages/editor.component.html",
            "shell/inspector-rail.component.ts"
        ]
    },
    {
        "icon": "sparkle",
        "count": 7,
        "labels": [
            "t().editor.ai.fixDocument",
            "t().editor.ai.schizoDocument"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/glossary-term-form.component.html"
        ]
    },
    {
        "icon": "translate",
        "count": 7,
        "labels": [
            "triggerTitle()"
        ],
        "files": [
            "pages/glossary.component.html",
            "pages/project-dialogue.component.html",
            "pages/settings.component.html",
            "shared/glossary-term-form.component.html",
            "shared/language-menu.component.ts"
        ]
    },
    {
        "icon": "arrow-counter-clockwise",
        "count": 6,
        "labels": [
            "d.isArchived ? t().drafts.actions.unarchive : t().drafts.actions.archive",
            "t().manager.forms.restoreAccess"
        ],
        "files": [
            "pages/ai-operations.component.html",
            "pages/drafts.component.html",
            "pages/forms.component.html",
            "pages/posts-manager.component.html",
            "pages/project-assets.component.html"
        ]
    },
    {
        "icon": "caret-left",
        "count": 6,
        "labels": [
            "periodBackTitle()",
            "t().editor.frame.back"
        ],
        "files": [
            "pages/calendar.component.html",
            "pages/editor.component.html",
            "pages/glossary.component.html",
            "pages/media-library.component.html",
            "pages/settings.component.html",
            "shared/media-picker.component.html"
        ]
    },
    {
        "icon": "file-text",
        "count": 6,
        "labels": [
            "doc.title",
            "t().editor.inspector.document",
            "task.title"
        ],
        "files": [
            "pages/project-assets.component.html",
            "pages/project-builds.component.html",
            "pages/project-tasks.component.html",
            "pages/project.component.html",
            "shared/document-outline.component.ts",
            "shell/document-frame.component.ts"
        ]
    },
    {
        "icon": "folder-open",
        "count": 5,
        "labels": [],
        "files": [
            "pages/project-assets.component.html",
            "pages/projects.component.html",
            "shell/project-switcher.component.ts"
        ]
    },
    {
        "icon": "table",
        "count": 5,
        "labels": [
            "t().editor.tableMenu.insert",
            "t().editor.tb.table"
        ],
        "files": [
            "pages/editor-preview/editor-preview.component.ts",
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "arrow-up",
        "count": 4,
        "labels": [
            "t().drafts.tree.moveUp",
            "t().projects.canvas.bringToFront",
            "t().projects.showcase.moveUp"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/project-canvas.component.html",
            "pages/project-showcase.component.html",
            "pages/project.component.html"
        ]
    },
    {
        "icon": "gear",
        "count": 4,
        "labels": [
            "\n                    t().projects.hub.customizeSection + ': ' + sectionTitle(panel.id)\n                  ",
            "t().editor.previewTab.manage",
            "t().projects.settings",
            "t().shell.settings"
        ],
        "files": [
            "pages/editor-preview/preview-destinations.component.ts",
            "pages/project.component.html",
            "shared/account-menu.component.ts"
        ]
    },
    {
        "icon": "squares-four",
        "count": 4,
        "labels": [
            "board.name || t().projects.canvas.untitledBoard t().projects.canvas.itemCount(board.itemCount) · backgroundWord(board.background)",
            "p.name",
            "t().editor.tb.collage"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-boards.component.html",
            "pages/projects.component.html"
        ]
    },
    {
        "icon": "tree-evergreen",
        "count": 4,
        "labels": [
            "t().drafts.actions.evergreen"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/projects.component.html"
        ]
    },
    {
        "icon": "arrow-down",
        "count": 3,
        "labels": [
            "t().drafts.tree.moveDown",
            "t().projects.showcase.moveDown"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/project-showcase.component.html",
            "pages/project.component.html"
        ]
    },
    {
        "icon": "arrows-out-simple",
        "count": 3,
        "labels": [
            "t().drafts.resetColumns",
            "t().projects.canvas.zoomFit",
            "t().projects.dialogues.zoomFit"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/project-canvas.component.html",
            "pages/project-dialogue.component.html"
        ]
    },
    {
        "icon": "circle-notch",
        "count": 3,
        "labels": [
            "(busy spinner)"
        ],
        "files": [
            "pages/editor-preview/editor-preview.component.ts",
            "pages/editor-preview/preview-checks.component.ts",
            "pages/project-assets.component.html"
        ]
    },
    {
        "icon": "eye",
        "count": 3,
        "labels": [
            "t().projects.openDocument"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/project.component.html"
        ]
    },
    {
        "icon": "list-numbers",
        "count": 3,
        "labels": [
            "t().drafts.series.title"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-builds.component.html",
            "shared/series-picker.component.html"
        ]
    },
    {
        "icon": "newspaper",
        "count": 3,
        "labels": [
            "destinationName(d)"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/presets.component.html",
            "pages/project-planner.component.html"
        ]
    },
    {
        "icon": "tree-structure",
        "count": 3,
        "labels": [
            "script.name t().projects.dialogues.nodeCount(script.nodeCount)",
            "t().drafts.tree.move"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/project-dialogues.component.html"
        ]
    },
    {
        "icon": "upload-simple",
        "count": 3,
        "labels": [],
        "files": [
            "pages/media-library.component.html",
            "shared/media-picker.component.html"
        ]
    },
    {
        "icon": "user",
        "count": 3,
        "labels": [
            "team.name t().teams.memberCount(team.activeCount, team.memberCount) · t().teams.projectCount(team.projectCount)",
            "team.name t().teams.ownedBy(team.ownerName) · roleWord(team.role) · statusWord(team.status)"
        ],
        "files": [
            "pages/admin.component.html",
            "pages/teams.component.html"
        ]
    },
    {
        "icon": "book-bookmark",
        "count": 2,
        "labels": [
            "t().glossary.createFromSelection"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "calendar-blank",
        "count": 2,
        "labels": [],
        "files": [
            "pages/calendar.component.html",
            "shell/document-frame.component.ts"
        ]
    },
    {
        "icon": "chat-teardrop",
        "count": 2,
        "labels": [
            "alertsTitle() || null",
            "t().editor.tb.annotation"
        ],
        "files": [
            "pages/editor.component.html",
            "shell/sidebar.component.ts"
        ]
    },
    {
        "icon": "chat-teardrop-dots",
        "count": 2,
        "labels": [
            "feedbackLabel()"
        ],
        "files": [
            "shared/feedback-panel.component.ts",
            "shell/sidebar.component.ts"
        ]
    },
    {
        "icon": "clipboard-text",
        "count": 2,
        "labels": [
            "t().editor.exportModal.copied t().editor.exportModal.copyFor(target.name)"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/form-ref.component.html"
        ]
    },
    {
        "icon": "dots-three",
        "count": 2,
        "labels": [
            "t().editor.groups.more"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "drop",
        "count": 2,
        "labels": [
            "t().ai.openBilling",
            "t().shell.credits(n)"
        ],
        "files": [
            "pages/ai-operations.component.html",
            "shared/account-menu.component.ts"
        ]
    },
    {
        "icon": "eye-slash",
        "count": 2,
        "labels": [
            "blockTitle(block) blockLabel(block.kind)"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-showcase.component.html"
        ]
    },
    {
        "icon": "file-arrow-up",
        "count": 2,
        "labels": [],
        "files": [
            "pages/project-dialogue.component.html",
            "pages/project-tasks.component.html"
        ]
    },
    {
        "icon": "flag",
        "count": 2,
        "labels": [
            "t().location.useProfile(home)"
        ],
        "files": [
            "pages/project-tasks.component.html",
            "shared/location-input.component.ts"
        ]
    },
    {
        "icon": "globe",
        "count": 2,
        "labels": [],
        "files": [
            "pages/project.component.html",
            "shared/publish-matrix.component.ts"
        ]
    },
    {
        "icon": "heart",
        "count": 2,
        "labels": [],
        "files": [
            "pages/drafts.component.html"
        ]
    },
    {
        "icon": "images",
        "count": 2,
        "labels": [
            "t().editor.tb.carousel"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-assets.component.html"
        ]
    },
    {
        "icon": "list",
        "count": 2,
        "labels": [
            "t().projects.hub.dragSection"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project.component.html"
        ]
    },
    {
        "icon": "list-checks",
        "count": 2,
        "labels": [],
        "files": [
            "pages/editor.component.html",
            "pages/project-showcase.component.html"
        ]
    },
    {
        "icon": "note",
        "count": 2,
        "labels": [],
        "files": [
            "pages/project-canvas.component.html"
        ]
    },
    {
        "icon": "prohibit",
        "count": 2,
        "labels": [
            "t().manager.forms.revokeAccess"
        ],
        "files": [
            "pages/forms.component.html"
        ]
    },
    {
        "icon": "sigma",
        "count": 2,
        "labels": [
            "t().editor.tb.formula"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "sign-out",
        "count": 2,
        "labels": [
            "t().editor.logout"
        ],
        "files": [
            "shared/account-menu.component.ts",
            "shell/app-shell.component.ts"
        ]
    },
    {
        "icon": "smiley",
        "count": 2,
        "labels": [
            "t().editor.tb.emoji"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-superscript",
        "count": 2,
        "labels": [
            "t().editor.tb.footnote"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "thumbs-down",
        "count": 2,
        "labels": [
            "t().feedback.dislikes"
        ],
        "files": [
            "pages/comments.component.html"
        ]
    },
    {
        "icon": "thumbs-up",
        "count": 2,
        "labels": [
            "t().feedback.likes"
        ],
        "files": [
            "pages/comments.component.html"
        ]
    },
    {
        "icon": "arrow-u-up-left",
        "count": 1,
        "labels": [
            "t().editor.tb.undo"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "arrow-u-up-right",
        "count": 1,
        "labels": [
            "t().editor.tb.redo"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "check-square",
        "count": 1,
        "labels": [
            "t().editor.tb.poll"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "code",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "code-block",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "desktop",
        "count": 1,
        "labels": [
            "t().editor.previewTab.desktop"
        ],
        "files": [
            "pages/editor-preview/editor-preview.component.ts"
        ]
    },
    {
        "icon": "device-mobile",
        "count": 1,
        "labels": [
            "t().editor.previewTab.mobile"
        ],
        "files": [
            "pages/editor-preview/editor-preview.component.ts"
        ]
    },
    {
        "icon": "file",
        "count": 1,
        "labels": [],
        "files": [
            "pages/project-tasks.component.html"
        ]
    },
    {
        "icon": "film-slate",
        "count": 1,
        "labels": [],
        "files": [
            "pages/project-showcase.component.html"
        ]
    },
    {
        "icon": "folder",
        "count": 1,
        "labels": [
            "t().drafts.folders.filter"
        ],
        "files": [
            "shared/folder-picker.component.html"
        ]
    },
    {
        "icon": "list-bullets",
        "count": 1,
        "labels": [
            "t().editor.tb.toc"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "list-dashes",
        "count": 1,
        "labels": [
            "t().editor.tb.toggleBlock"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "magnifying-glass",
        "count": 1,
        "labels": [],
        "files": [
            "shared/search-overlay.component.html"
        ]
    },
    {
        "icon": "quotes",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "rows",
        "count": 1,
        "labels": [
            "t().editor.tb.divider"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "terminal-window",
        "count": 1,
        "labels": [],
        "files": [
            "shared/command-palette.component.html"
        ]
    },
    {
        "icon": "text-align-center",
        "count": 1,
        "labels": [
            "t().editor.tb.alignCenter"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-align-justify",
        "count": 1,
        "labels": [
            "t().editor.tb.alignJustify"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-align-left",
        "count": 1,
        "labels": [
            "t().editor.tb.alignLeft"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-align-right",
        "count": 1,
        "labels": [
            "t().editor.tb.alignRight"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-b",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-indent",
        "count": 1,
        "labels": [
            "t().editor.tb.indent"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-italic",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-outdent",
        "count": 1,
        "labels": [
            "t().editor.tb.outdent"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-strikethrough",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-underline",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "video-camera",
        "count": 1,
        "labels": [
            "t().editor.tb.video"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "waveform",
        "count": 1,
        "labels": [
            "t().editor.tb.audio"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    }
];
