// GENERATED by tools/generate-icon-usage.mjs — do not edit by hand.
// Every app-icon call site in src/app, with the label its control carries (T-080).
// 76 distinct icons across 239 call sites.

export interface IconUsageRow {
    /** Icon name, or "(dynamic)" where the template binds [name] to an expression. */
    icon: string;
    count: number;
    /** The accessible names this icon appears under — a raw t() path, or literal text. */
    labels: string[];
    files: string[];
}

export const ICON_USAGE: IconUsageRow[] = [
    {
        "icon": "arrow-clockwise",
        "count": 24,
        "labels": [
            "(busy spinner)",
            "t().editor.exportModal.resend",
            "t().manager.forms.translateLang"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/glossary.component.html",
            "pages/posts-manager.component.html",
            "pages/settings.component.html",
            "shared/debug-console.component.html",
            "shared/glossary-term-form.component.ts"
        ]
    },
    {
        "icon": "x",
        "count": 18,
        "labels": [
            "p.status === 'Pending' ? t().manager.cancelScheduled : t().manager.removeFromList",
            "t().common.cancel",
            "t().common.close",
            "t().common.delete",
            "t().editor.exportModal.changeChannel",
            "t().editor.exportModal.detachAsset",
            "t().editor.exportModal.revoke",
            "t().editor.tags.deleteEverywhere",
            "t().manager.forms.removeLang",
            "t().manager.forms.removeOption",
            "t().manager.forms.removeQuestion"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/posts-manager.component.html",
            "shared/debug-console.component.html",
            "shared/folder-picker.component.html",
            "shared/glossary-term-form.component.ts",
            "shared/modal.component.html",
            "shared/tag-picker.component.html"
        ]
    },
    {
        "icon": "trash",
        "count": 16,
        "labels": [
            "t().common.delete",
            "t().debug.clear",
            "t().drafts.actions.deleteDraft",
            "t().editor.lang.deleteTranslation",
            "t().feedback.deleteComment",
            "t().manager.forms.deleteSubmission"
        ],
        "files": [
            "pages/comments.component.html",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/glossary.component.html",
            "pages/posts-manager.component.html",
            "shared/debug-console.component.html",
            "shared/folder-picker.component.html",
            "shared/tag-picker.component.html"
        ]
    },
    {
        "icon": "info",
        "count": 15,
        "labels": [],
        "files": [
            "pages/editor.component.html",
            "pages/glossary.component.html",
            "pages/posts-manager.component.html"
        ]
    },
    {
        "icon": "check",
        "count": 13,
        "labels": [
            "t().common.save"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/settings.component.html"
        ]
    },
    {
        "icon": "plus",
        "count": 12,
        "labels": [
            "t().drafts.folders.add",
            "t().drafts.newDraft",
            "t().editor.exportModal.invite",
            "t().glossary.newTerm",
            "t().projects.newDocument",
            "t().projects.newProject"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/glossary.component.html",
            "pages/project.component.html",
            "pages/projects.component.html",
            "shared/folder-picker.component.html"
        ]
    },
    {
        "icon": "lock",
        "count": 8,
        "labels": [
            "d.isPrivate ? t().manager.makePublic : t().manager.makePrivate",
            "d.title || t().drafts.untitled publishStateLabel(d) l.toUpperCase() + extra t().manager.privateChip + n"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/posts-manager.component.html",
            "pages/settings.component.html"
        ]
    },
    {
        "icon": "(dynamic)",
        "count": 7,
        "labels": [
            "t().projects.docTypes[type].name t().projects.docTypes[type].blurb",
            "t().projects.projectTypes[type].name t().projects.projectTypes[type].blurb t().projects.create.startsWith(t().projects.projectTypes[type].starter)"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project.component.html",
            "pages/projects.component.html"
        ]
    },
    {
        "icon": "translate",
        "count": 6,
        "labels": [
            "t().glossary.translate",
            "t().glossary.translateAll",
            "t().settings.profile.translateInto(signatureLanguage().toUpperCase())",
            "t().settings.profile.translateTexts"
        ],
        "files": [
            "pages/glossary.component.html",
            "pages/settings.component.html"
        ]
    },
    {
        "icon": "book-bookmark",
        "count": 5,
        "labels": [
            "t().glossary.createFromSelection",
            "t().glossary.open"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/glossary.component.html",
            "shared/page-header.component.html"
        ]
    },
    {
        "icon": "paper-plane-tilt",
        "count": 5,
        "labels": [
            "creditsBusy() ? '…' : t().settings.credits.buy(packPriceUsd(selectedPackPriceCents()))",
            "t().editor.export"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/settings.component.html"
        ]
    },
    {
        "icon": "sparkle",
        "count": 5,
        "labels": [
            "t().editor.ai.fixLabel",
            "t().editor.ai.schizoLabel",
            "t().editor.tb.ai",
            "t().glossary.suggestForms"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/glossary-term-form.component.ts"
        ]
    },
    {
        "icon": "warning",
        "count": 5,
        "labels": [],
        "files": [
            "pages/drafts.component.html"
        ]
    },
    {
        "icon": "clock",
        "count": 4,
        "labels": [
            "d.title || t().drafts.untitled publishStateLabel(d) l.toUpperCase() + extra t().manager.privateChip + n",
            "t().editor.tb.datetime"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/posts-manager.component.html"
        ]
    },
    {
        "icon": "newspaper",
        "count": 4,
        "labels": [
            "t().editor.postsManager"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/page-header.component.html"
        ]
    },
    {
        "icon": "archive",
        "count": 3,
        "labels": [
            "d.isArchived ? t().drafts.actions.unarchive : t().drafts.actions.archive",
            "t().manager.unarchive t().manager.archive"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/posts-manager.component.html"
        ]
    },
    {
        "icon": "arrow-counter-clockwise",
        "count": 3,
        "labels": [
            "d.isArchived ? t().drafts.actions.unarchive : t().drafts.actions.archive",
            "t().manager.unarchive t().manager.archive"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/posts-manager.component.html"
        ]
    },
    {
        "icon": "download-simple",
        "count": 3,
        "labels": [
            "t().editor.exportModal.downloadCedar",
            "t().editor.exportModal.downloadZip"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "gear",
        "count": 3,
        "labels": [
            "t().editor.settings",
            "t().projects.settings"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project.component.html",
            "shared/page-header.component.html"
        ]
    },
    {
        "icon": "image",
        "count": 3,
        "labels": [
            "t().editor.tb.image"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/glossary-term-form.component.ts"
        ]
    },
    {
        "icon": "link",
        "count": 3,
        "labels": [
            "t().editor.exportModal.copyInvite",
            "t().editor.tb.insert"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "pencil-simple",
        "count": 3,
        "labels": [
            "t().common.edit",
            "t().drafts.folders.rename",
            "t().editor.tags.rename"
        ],
        "files": [
            "pages/glossary.component.html",
            "shared/folder-picker.component.html",
            "shared/tag-picker.component.html"
        ]
    },
    {
        "icon": "shield-check",
        "count": 3,
        "labels": [
            "t().admin.open"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/account-menu.component.ts",
            "shared/page-header.component.html"
        ]
    },
    {
        "icon": "sigma",
        "count": 3,
        "labels": [
            "Block formula",
            "Inline formula",
            "t().editor.tb.formula"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "arrow-square-out",
        "count": 2,
        "labels": [
            "t().manager.openBlog",
            "t().manager.openTelegram"
        ],
        "files": [
            "pages/posts-manager.component.html"
        ]
    },
    {
        "icon": "eye",
        "count": 2,
        "labels": [],
        "files": [
            "pages/drafts.component.html"
        ]
    },
    {
        "icon": "file-arrow-up",
        "count": 2,
        "labels": [
            "(busy spinner)"
        ],
        "files": [
            "pages/drafts.component.html"
        ]
    },
    {
        "icon": "folder",
        "count": 2,
        "labels": [
            "t().drafts.folders.filter"
        ],
        "files": [
            "pages/drafts.component.html",
            "shared/folder-picker.component.html"
        ]
    },
    {
        "icon": "game-controller",
        "count": 2,
        "labels": [
            "t().projects.crumb"
        ],
        "files": [
            "pages/projects.component.html",
            "shared/page-header.component.html"
        ]
    },
    {
        "icon": "heart",
        "count": 2,
        "labels": [],
        "files": [
            "pages/drafts.component.html"
        ]
    },
    {
        "icon": "layout",
        "count": 2,
        "labels": [
            "d.isTemplate ? t().drafts.actions.unmarkTemplate : t().drafts.actions.markTemplate"
        ],
        "files": [
            "pages/drafts.component.html"
        ]
    },
    {
        "icon": "list",
        "count": 2,
        "labels": [
            "t().drafts.viewTable"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "palette",
        "count": 2,
        "labels": [
            "t().settings.appearance.title"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/appearance-panel.component.html"
        ]
    },
    {
        "icon": "smiley",
        "count": 2,
        "labels": [
            "t().editor.tb.emoji"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "squares-four",
        "count": 2,
        "labels": [
            "t().drafts.viewGrid",
            "t().editor.tb.collage"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "table",
        "count": 2,
        "labels": [
            "Insert table",
            "t().editor.tb.table"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "terminal-window",
        "count": 2,
        "labels": [
            "t().debug.console",
            "t().debug.console inFlightCount() errorCount()"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/debug-console.component.html"
        ]
    },
    {
        "icon": "arrow-left",
        "count": 1,
        "labels": [
            "t().common.backToEditor"
        ],
        "files": [
            "shared/page-header.component.html"
        ]
    },
    {
        "icon": "arrow-u-up-left",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "arrow-u-up-right",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "arrows-in-simple",
        "count": 1,
        "labels": [
            "isFullscreen() ? t().editor.exitFullscreen : t().editor.enterFullscreen"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "arrows-out-simple",
        "count": 1,
        "labels": [
            "isFullscreen() ? t().editor.exitFullscreen : t().editor.enterFullscreen"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "caret-down",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "chat-teardrop",
        "count": 1,
        "labels": [
            "t().editor.tb.annotation"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "check-square",
        "count": 1,
        "labels": [
            "t().editor.tb.poll"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "clipboard-text",
        "count": 1,
        "labels": [],
        "files": [
            "shared/form-ref.component.html"
        ]
    },
    {
        "icon": "code",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "code-block",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "drop",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "eye-slash",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "files",
        "count": 1,
        "labels": [
            "t().editor.drafts"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "images",
        "count": 1,
        "labels": [
            "t().editor.tb.carousel"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "kanban",
        "count": 1,
        "labels": [],
        "files": [
            "pages/project.component.html"
        ]
    },
    {
        "icon": "list-bullets",
        "count": 1,
        "labels": [
            "t().editor.tb.toc"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "list-checks",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "list-dashes",
        "count": 1,
        "labels": [
            "t().editor.tb.toggleBlock"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "list-numbers",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "pen",
        "count": 1,
        "labels": [
            "t().manager.openInEditor"
        ],
        "files": [
            "pages/posts-manager.component.html"
        ]
    },
    {
        "icon": "quotes",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "rows",
        "count": 1,
        "labels": [
            "t().editor.tb.divider"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "sign-out",
        "count": 1,
        "labels": [
            "t().editor.logout"
        ],
        "files": [
            "shared/account-menu.component.ts"
        ]
    },
    {
        "icon": "text-align-center",
        "count": 1,
        "labels": [
            "t().editor.tb.alignCenter"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-align-justify",
        "count": 1,
        "labels": [
            "t().editor.tb.alignJustify"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-align-left",
        "count": 1,
        "labels": [
            "t().editor.tb.alignLeft"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-align-right",
        "count": 1,
        "labels": [
            "t().editor.tb.alignRight"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-b",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-indent",
        "count": 1,
        "labels": [
            "t().editor.tb.indent"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-italic",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-outdent",
        "count": 1,
        "labels": [
            "t().editor.tb.outdent"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-strikethrough",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-superscript",
        "count": 1,
        "labels": [
            "t().editor.tb.footnote"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-underline",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "upload-simple",
        "count": 1,
        "labels": [
            "(busy spinner)"
        ],
        "files": [
            "pages/drafts.component.html"
        ]
    },
    {
        "icon": "user",
        "count": 1,
        "labels": [
            "t().settings.tabs.profile"
        ],
        "files": [
            "shared/account-menu.component.ts"
        ]
    },
    {
        "icon": "video-camera",
        "count": 1,
        "labels": [
            "t().editor.tb.video"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "waveform",
        "count": 1,
        "labels": [
            "t().editor.tb.audio"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    }
];
