// GENERATED by tools/generate-icon-usage.mjs — do not edit by hand.
// Every app-icon call site in src/app, with the label its control carries (T-080).
// 86 distinct icons across 421 call sites.

export interface IconUsageRow {
    /** Icon name, or "(dynamic)" where the template binds [name] to an expression. */
    icon: string;
    count: number;
    /** The accessible names this icon appears under — a raw t() path, or literal text. */
    labels: string[];
    files: string[];
}

export const ICON_USAGE: IconUsageRow[] = [
    {
        "icon": "(dynamic)",
        "count": 41,
        "labels": [
            "a.fileName",
            "a.fileName a.contentType bytes(a.sizeBytes) a.createdAt | zonedDate:'MM/dd/yyyy'",
            "baseTypeName(type)",
            "hit.title || t().drafts.untitled hit.snippet t().search.published",
            "item.label ? null : (item.title || null)",
            "preset.name presetConfig(preset).headings.length ? presetConfig(preset).headings.join(' · ') : t().presets.noSkeleton t().presets.documentPresets",
            "slot.isActive ? t().calendar.queue.pause : t().calendar.queue.resume",
            "t().common.toggleTheme",
            "t().drafts.columns.activity",
            "t().drafts.columns.folder",
            "t().drafts.columns.languages",
            "t().drafts.columns.state",
            "t().drafts.columns.tags",
            "t().drafts.columns.title",
            "t().drafts.columns.updated",
            "t().projects.assets.notFoundAtPath t().projects.assets.previewPending t().projects.assets.noPreview(t().projects.assets.kindOne[a.kind]) t().projects.assets.fingerprint a.fileName detailsOf(a) · a.modifiedAt | zonedDate:'MM/dd'",
            "t().projects.docTypes[type].name t().projects.docTypes[type].blurb isPublishableType(type) ? t().projects.newDoc.publishes : t().projects.newDoc.workingMaterial",
            "t().projects.openDocument",
            "t().projects.projectTypes[type].name t().projects.projectTypes[type].blurb t().projects.create.startsWith(t().projects.projectTypes[type].starter)"
        ],
        "files": [
            "bench/chrome/bench-shell.component.ts",
            "bench/chrome/hook-rail.component.ts",
            "bench/worktop/module-tile.component.ts",
            "pages/calendar.component.html",
            "pages/download.component.html",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/login.component.html",
            "pages/media-library.component.html",
            "pages/onboarding.component.html",
            "pages/presets.component.html",
            "pages/project-assets.component.html",
            "pages/project-tasks.component.html",
            "pages/project.component.html",
            "pages/projects.component.html",
            "pages/register.component.html",
            "shared/document-outline.component.ts",
            "shared/legal-page.component.html",
            "shared/media-picker.component.html",
            "shared/search-overlay.component.html"
        ]
    },
    {
        "icon": "plus",
        "count": 31,
        "labels": [
            "doc.title",
            "t().drafts.folders.add",
            "t().drafts.series.add",
            "t().editor.exportModal.ctaAdd",
            "t().editor.exportModal.invite",
            "t().projects.tasks.newTask",
            "t().stats.inviteLinks.create"
        ],
        "files": [
            "pages/calendar.component.html",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/glossary.component.html",
            "pages/posts-manager.component.html",
            "pages/presets.component.html",
            "pages/project-assets.component.html",
            "pages/project-boards.component.html",
            "pages/project-builds.component.html",
            "pages/project-dialogue.component.html",
            "pages/project-dialogues.component.html",
            "pages/project-planner.component.html",
            "pages/project-tasks.component.html",
            "pages/project.component.html",
            "pages/projects.component.html",
            "pages/stats.component.html",
            "shared/folder-picker.component.html",
            "shared/series-picker.component.html"
        ]
    },
    {
        "icon": "x",
        "count": 30,
        "labels": [
            "p.status === 'Pending' ? t().manager.cancelScheduled : t().manager.removeFromList",
            "removeLabel() || null",
            "t().common.cancel",
            "t().common.cancel · aiEditProgress() %",
            "t().common.close",
            "t().common.delete",
            "t().editor.exportModal.changeChannel",
            "t().editor.exportModal.ctaRemove",
            "t().editor.exportModal.detachAsset",
            "t().editor.exportModal.revoke",
            "t().editor.tags.deleteEverywhere",
            "t().manager.forms.removeLang",
            "t().manager.forms.removeOption",
            "t().manager.forms.removeQuestion",
            "t().projects.assets.unlink",
            "t().projects.tasks.removeFile",
            "t().projects.tasks.unlink",
            "t().stats.inviteLinks.revoke"
        ],
        "files": [
            "bench/display/leaf-tag.component.ts",
            "pages/editor.component.html",
            "pages/media-library.component.html",
            "pages/posts-manager.component.html",
            "pages/project-assets.component.html",
            "pages/project-boards.component.html",
            "pages/project-tasks.component.html",
            "pages/stats.component.html",
            "shared/folder-picker.component.html",
            "shared/glossary-term-form.component.ts",
            "shared/modal.component.html",
            "shared/series-picker.component.html",
            "shared/tag-picker.component.html"
        ]
    },
    {
        "icon": "arrow-clockwise",
        "count": 25,
        "labels": [
            "(busy spinner)",
            "auth.hasAiPlan() ? t().manager.forms.translateLang : t().planLock.pro",
            "t().editor.exportModal.resend",
            "t().editor.syncFailedRetry"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/glossary.component.html",
            "pages/posts-manager.component.html",
            "pages/project-assets.component.html",
            "pages/settings.component.html",
            "shared/glossary-term-form.component.ts",
            "shared/media-picker.component.html"
        ]
    },
    {
        "icon": "trash",
        "count": 25,
        "labels": [
            "t().calendar.queue.remove",
            "t().common.delete",
            "t().debug.clear",
            "t().drafts.actions.deleteDraft",
            "t().editor.lang.deleteTranslation",
            "t().feedback.deleteComment",
            "t().manager.forms.deleteSubmission"
        ],
        "files": [
            "pages/admin.component.html",
            "pages/calendar.component.html",
            "pages/comments.component.html",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/glossary.component.html",
            "pages/posts-manager.component.html",
            "pages/presets.component.html",
            "pages/project-boards.component.html",
            "pages/project-canvas.component.html",
            "pages/project-dialogue.component.html",
            "pages/project-dialogues.component.html",
            "shared/debug-console.component.html",
            "shared/folder-picker.component.html",
            "shared/series-picker.component.html",
            "shared/tag-picker.component.html"
        ]
    },
    {
        "icon": "info",
        "count": 19,
        "labels": [
            "t().common.about"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/hint-dot.component.ts"
        ]
    },
    {
        "icon": "warning",
        "count": 18,
        "labels": [
            "t().projects.assets.notFoundAtPath t().projects.assets.previewPending t().projects.assets.noPreview(t().projects.assets.kindOne[a.kind]) t().projects.assets.fingerprint a.fileName detailsOf(a) · a.modifiedAt | zonedDate:'MM/dd'"
        ],
        "files": [
            "pages/calendar.component.html",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/onboarding.component.html",
            "pages/project-assets.component.html",
            "pages/project-boards.component.html",
            "pages/project-dialogue.component.html",
            "pages/project-dialogues.component.html"
        ]
    },
    {
        "icon": "check",
        "count": 17,
        "labels": [
            "t().common.save",
            "t().common.saved t().editor.exportModal.ctaSave",
            "t().editor.exportModal.copied t().editor.exportModal.copyFor(target.name)",
            "t().editor.exportModal.copied t().editor.exportModal.trackedLinkCopy(l.toUpperCase())",
            "t().editor.exportModal.trackedLinkCustomCopy"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/settings.component.html",
            "shared/feedback-panel.component.ts"
        ]
    },
    {
        "icon": "link",
        "count": 12,
        "labels": [
            "t().editor.exportModal.copied t().editor.exportModal.trackedLinkCopy(l.toUpperCase())",
            "t().editor.exportModal.copyInvite",
            "t().editor.exportModal.trackedLinkCustomCopy",
            "t().editor.preview.shareTitle",
            "t().editor.tb.insert",
            "t().stats.inviteLinks.copy"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-assets.component.html",
            "pages/project-boards.component.html",
            "pages/project-canvas.component.html",
            "pages/project-tasks.component.html",
            "pages/stats.component.html"
        ]
    },
    {
        "icon": "pencil-simple",
        "count": 11,
        "labels": [
            "t().common.edit",
            "t().drafts.folders.rename",
            "t().drafts.series.rename",
            "t().editor.tags.rename"
        ],
        "files": [
            "pages/glossary.component.html",
            "pages/presets.component.html",
            "pages/project-boards.component.html",
            "pages/project-builds.component.html",
            "pages/project-dialogues.component.html",
            "pages/project-planner.component.html",
            "pages/project.component.html",
            "shared/folder-picker.component.html",
            "shared/series-picker.component.html",
            "shared/tag-picker.component.html"
        ]
    },
    {
        "icon": "caret-down",
        "count": 8,
        "labels": [
            "isCollapsed(row.d.id) ? t().drafts.tree.expand : t().drafts.tree.collapse",
            "project()",
            "t().editor.tb.expandableQuote",
            "triggerTitle()"
        ],
        "files": [
            "bench/chrome/bench-drawer.component.ts",
            "bench/chrome/rail-header.component.ts",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/project-planner.component.html",
            "shared/language-menu.component.ts"
        ]
    },
    {
        "icon": "translate",
        "count": 8,
        "labels": [
            "t().glossary.translate",
            "triggerTitle()"
        ],
        "files": [
            "pages/glossary.component.html",
            "pages/project-dialogue.component.html",
            "pages/settings.component.html",
            "shared/language-menu.component.ts"
        ]
    },
    {
        "icon": "archive",
        "count": 7,
        "labels": [
            "(busy spinner)",
            "d.isArchived ? t().drafts.actions.unarchive : t().drafts.actions.archive",
            "t().editor.tb.library",
            "t().manager.unarchive t().manager.archive"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/posts-manager.component.html",
            "shared/media-picker.component.html"
        ]
    },
    {
        "icon": "lock",
        "count": 7,
        "labels": [
            "d.isPrivate ? t().manager.makePublic : t().manager.makePrivate",
            "d.title || t().drafts.untitled publishStateLabel(d) l.toUpperCase() + extra t().manager.privateChip + n",
            "title()"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/posts-manager.component.html",
            "pages/project-canvas.component.html",
            "shared/plan-lock.component.ts"
        ]
    },
    {
        "icon": "sparkle",
        "count": 7,
        "labels": [
            "t().editor.ai.fixDocument",
            "t().editor.ai.schizoDocument",
            "t().settings.tabs.account"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/account-menu.component.ts",
            "shared/glossary-term-form.component.ts"
        ]
    },
    {
        "icon": "squares-four",
        "count": 7,
        "labels": [
            "board.name || t().projects.canvas.untitledBoard t().projects.canvas.itemCount(board.itemCount) · backgroundWord(board.background)",
            "t().editor.tb.collage",
            "t().presets.crumb",
            "t().shell.icons"
        ],
        "files": [
            "bench/chrome/bench-shell.component.ts",
            "pages/editor.component.html",
            "pages/presets.component.html",
            "pages/project-boards.component.html",
            "pages/projects.component.html"
        ]
    },
    {
        "icon": "caret-left",
        "count": 6,
        "labels": [],
        "files": [
            "pages/calendar.component.html",
            "pages/glossary.component.html",
            "pages/media-library.component.html",
            "pages/project-assets.component.html",
            "pages/settings.component.html",
            "shared/media-picker.component.html"
        ]
    },
    {
        "icon": "caret-right",
        "count": 6,
        "labels": [],
        "files": [
            "pages/calendar.component.html",
            "pages/glossary.component.html",
            "pages/media-library.component.html",
            "pages/project-assets.component.html",
            "pages/settings.component.html",
            "shared/media-picker.component.html"
        ]
    },
    {
        "icon": "paper-plane-tilt",
        "count": 6,
        "labels": [],
        "files": [
            "pages/editor.component.html",
            "pages/project-boards.component.html",
            "pages/settings.component.html"
        ]
    },
    {
        "icon": "arrow-square-out",
        "count": 5,
        "labels": [
            "d.blogSlug",
            "linkOf(item).url",
            "t().manager.openTelegram",
            "t().manager.threadOf(post.partCount) t().manager.openPost(networkLabel(post.network))",
            "t().projects.showcase.openPage"
        ],
        "files": [
            "pages/posts-manager.component.html",
            "pages/project-canvas.component.html",
            "pages/project-showcase.component.html"
        ]
    },
    {
        "icon": "clock",
        "count": 5,
        "labels": [
            "d.title || t().drafts.untitled publishStateLabel(d) l.toUpperCase() + extra t().manager.privateChip + n",
            "t().editor.tb.datetime"
        ],
        "files": [
            "pages/calendar.component.html",
            "pages/editor.component.html",
            "pages/posts-manager.component.html"
        ]
    },
    {
        "icon": "download-simple",
        "count": 5,
        "labels": [
            "(busy spinner)",
            "t().editor.exportModal.downloadCedar",
            "t().editor.exportModal.downloadZip"
        ],
        "files": [
            "pages/download.component.html",
            "pages/drafts.component.html",
            "pages/editor.component.html",
            "pages/project-dialogue.component.html"
        ]
    },
    {
        "icon": "image",
        "count": 5,
        "labels": [
            "t().editor.tb.image"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-canvas.component.html",
            "pages/project.component.html",
            "shared/glossary-term-form.component.ts"
        ]
    },
    {
        "icon": "layout",
        "count": 5,
        "labels": [
            "d.isTemplate ? t().drafts.actions.unmarkTemplate : t().drafts.actions.markTemplate"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/project-canvas.component.html"
        ]
    },
    {
        "icon": "tree-evergreen",
        "count": 5,
        "labels": [
            "t().drafts.actions.evergreen"
        ],
        "files": [
            "bench/chrome/bench-shell.component.ts",
            "pages/drafts.component.html",
            "pages/stats.component.html"
        ]
    },
    {
        "icon": "arrow-counter-clockwise",
        "count": 4,
        "labels": [
            "d.isArchived ? t().drafts.actions.unarchive : t().drafts.actions.archive",
            "t().manager.unarchive t().manager.archive"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/posts-manager.component.html",
            "pages/project-assets.component.html"
        ]
    },
    {
        "icon": "file-text",
        "count": 4,
        "labels": [
            "doc.title",
            "p.name",
            "t().editor.inspector.document"
        ],
        "files": [
            "pages/project-assets.component.html",
            "pages/project-builds.component.html",
            "pages/projects.component.html",
            "shared/document-outline.component.ts"
        ]
    },
    {
        "icon": "arrow-up",
        "count": 3,
        "labels": [
            "t().drafts.tree.moveUp"
        ],
        "files": [
            "pages/admin.component.html",
            "pages/drafts.component.html",
            "pages/project-canvas.component.html"
        ]
    },
    {
        "icon": "arrows-out-simple",
        "count": 3,
        "labels": [
            "t().drafts.resetColumns"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/project-canvas.component.html",
            "pages/project-dialogue.component.html"
        ]
    },
    {
        "icon": "book-bookmark",
        "count": 3,
        "labels": [
            "t().glossary.createFromSelection",
            "t().glossary.crumb"
        ],
        "files": [
            "bench/chrome/bench-shell.component.ts",
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "check-square",
        "count": 3,
        "labels": [
            "p.name",
            "t().editor.tb.poll"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-tasks.component.html",
            "pages/projects.component.html"
        ]
    },
    {
        "icon": "folder-open",
        "count": 3,
        "labels": [],
        "files": [
            "pages/project-assets.component.html"
        ]
    },
    {
        "icon": "images",
        "count": 3,
        "labels": [
            "p.name",
            "t().editor.tb.carousel"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-assets.component.html",
            "pages/projects.component.html"
        ]
    },
    {
        "icon": "list-numbers",
        "count": 3,
        "labels": [
            "t().drafts.series.title"
        ],
        "files": [
            "pages/editor.component.html",
            "pages/project-builds.component.html",
            "shared/series-picker.component.html"
        ]
    },
    {
        "icon": "newspaper",
        "count": 3,
        "labels": [],
        "files": [
            "pages/editor.component.html",
            "pages/project-planner.component.html"
        ]
    },
    {
        "icon": "palette",
        "count": 3,
        "labels": [
            "t().settings.appearance.title",
            "t().shell.styleguide"
        ],
        "files": [
            "bench/chrome/bench-shell.component.ts",
            "shared/appearance-panel.component.html"
        ]
    },
    {
        "icon": "table",
        "count": 3,
        "labels": [
            "t().editor.tableMenu.insert",
            "t().editor.tb.table"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "tree-structure",
        "count": 3,
        "labels": [
            "script.name t().projects.dialogues.nodeCount(script.nodeCount)",
            "t().drafts.tree.move"
        ],
        "files": [
            "pages/drafts.component.html",
            "pages/project-dialogues.component.html"
        ]
    },
    {
        "icon": "arrow-down",
        "count": 2,
        "labels": [
            "t().drafts.tree.moveDown"
        ],
        "files": [
            "pages/admin.component.html",
            "pages/drafts.component.html"
        ]
    },
    {
        "icon": "chat-teardrop-dots",
        "count": 2,
        "labels": [
            "t().feedbackForm.title"
        ],
        "files": [
            "bench/chrome/bench-shell.component.ts",
            "shared/feedback-panel.component.ts"
        ]
    },
    {
        "icon": "clipboard-text",
        "count": 2,
        "labels": [
            "t().editor.exportModal.copied t().editor.exportModal.copyFor(target.name)"
        ],
        "files": [
            "pages/editor.component.html",
            "shared/form-ref.component.html"
        ]
    },
    {
        "icon": "eye",
        "count": 2,
        "labels": [],
        "files": [
            "pages/drafts.component.html"
        ]
    },
    {
        "icon": "file-arrow-up",
        "count": 2,
        "labels": [],
        "files": [
            "pages/project-dialogue.component.html",
            "pages/project-tasks.component.html"
        ]
    },
    {
        "icon": "heart",
        "count": 2,
        "labels": [],
        "files": [
            "pages/drafts.component.html"
        ]
    },
    {
        "icon": "list",
        "count": 2,
        "labels": [],
        "files": [
            "pages/editor.component.html",
            "pages/project.component.html"
        ]
    },
    {
        "icon": "sigma",
        "count": 2,
        "labels": [
            "t().editor.tb.formula"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "smiley",
        "count": 2,
        "labels": [
            "t().editor.tb.emoji"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-superscript",
        "count": 2,
        "labels": [
            "t().editor.tb.footnote"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "timer",
        "count": 2,
        "labels": [],
        "files": [
            "pages/calendar.component.html",
            "pages/project-planner.component.html"
        ]
    },
    {
        "icon": "arrow-u-up-left",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "arrow-u-up-right",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "chat-teardrop",
        "count": 1,
        "labels": [
            "t().editor.tb.annotation"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "circle-notch",
        "count": 1,
        "labels": [
            "(busy spinner)"
        ],
        "files": [
            "pages/project-assets.component.html"
        ]
    },
    {
        "icon": "code",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "code-block",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "dots-three",
        "count": 1,
        "labels": [
            "trayLabel()"
        ],
        "files": [
            "bench/chrome/hook-rail.component.ts"
        ]
    },
    {
        "icon": "drop",
        "count": 1,
        "labels": [
            "t().shell.credits(credits)"
        ],
        "files": [
            "bench/chrome/bench-shell.component.ts"
        ]
    },
    {
        "icon": "eye-slash",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "file",
        "count": 1,
        "labels": [],
        "files": [
            "pages/project-tasks.component.html"
        ]
    },
    {
        "icon": "flag",
        "count": 1,
        "labels": [
            "t().location.useProfile(home)"
        ],
        "files": [
            "shared/location-input.component.ts"
        ]
    },
    {
        "icon": "folder",
        "count": 1,
        "labels": [
            "t().drafts.folders.filter"
        ],
        "files": [
            "shared/folder-picker.component.html"
        ]
    },
    {
        "icon": "gear",
        "count": 1,
        "labels": [],
        "files": [
            "pages/project.component.html"
        ]
    },
    {
        "icon": "list-bullets",
        "count": 1,
        "labels": [
            "t().editor.tb.toc"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "list-checks",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "list-dashes",
        "count": 1,
        "labels": [
            "t().editor.tb.toggleBlock"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "magnifying-glass",
        "count": 1,
        "labels": [],
        "files": [
            "shared/search-overlay.component.html"
        ]
    },
    {
        "icon": "note",
        "count": 1,
        "labels": [],
        "files": [
            "pages/project-canvas.component.html"
        ]
    },
    {
        "icon": "pen",
        "count": 1,
        "labels": [
            "t().manager.openInEditor"
        ],
        "files": [
            "pages/posts-manager.component.html"
        ]
    },
    {
        "icon": "quotes",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "rocket-launch",
        "count": 1,
        "labels": [],
        "files": [
            "pages/project-builds.component.html"
        ]
    },
    {
        "icon": "rows",
        "count": 1,
        "labels": [
            "t().editor.tb.divider"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "sign-out",
        "count": 1,
        "labels": [
            "t().editor.logout"
        ],
        "files": [
            "shared/account-menu.component.ts"
        ]
    },
    {
        "icon": "text-align-center",
        "count": 1,
        "labels": [
            "t().editor.tb.alignCenter"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-align-justify",
        "count": 1,
        "labels": [
            "t().editor.tb.alignJustify"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-align-left",
        "count": 1,
        "labels": [
            "t().editor.tb.alignLeft"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-align-right",
        "count": 1,
        "labels": [
            "t().editor.tb.alignRight"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-b",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-indent",
        "count": 1,
        "labels": [
            "t().editor.tb.indent"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-italic",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-outdent",
        "count": 1,
        "labels": [
            "t().editor.tb.outdent"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-strikethrough",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "text-underline",
        "count": 1,
        "labels": [],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "upload-simple",
        "count": 1,
        "labels": [],
        "files": [
            "shared/media-picker.component.html"
        ]
    },
    {
        "icon": "user",
        "count": 1,
        "labels": [
            "t().settings.tabs.profile"
        ],
        "files": [
            "shared/account-menu.component.ts"
        ]
    },
    {
        "icon": "video-camera",
        "count": 1,
        "labels": [
            "t().editor.tb.video"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    },
    {
        "icon": "waveform",
        "count": 1,
        "labels": [
            "t().editor.tb.audio"
        ],
        "files": [
            "pages/editor.component.html"
        ]
    }
];
