// T-079 — generates src/app/shared/icon-data.generated.ts from @phosphor-icons/core.
//
// Why a generated file rather than importing the package at runtime: the package ships raw .svg
// assets, and Angular has no loader for those without extra build configuration. Emitting the inner
// markup as a plain TS constant keeps the icons tree-shakeable, keeps the build config untouched,
// and means the icon set is a build-time dependency rather than something the browser fetches.
//
// Run: node tools/generate-icons.mjs   (from cedarclerk-web/)
// The output is committed — regenerate only when tools/icon-map.json changes.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const WEIGHTS = ['regular', 'bold'];
const map = JSON.parse(readFileSync(resolve(ROOT, 'tools/icon-map.json'), 'utf8'));

// Phosphor names are what the app will use from here on; several Lucide names collapse onto one
// (SigmaSquare/Sigma, Sparkle/Sparkles), which is the point — they were the same idea twice.
const names = [...new Set(Object.values(map))].sort();

const out = [];
out.push('// GENERATED by tools/generate-icons.mjs — do not edit by hand.');
out.push('// Source: @phosphor-icons/core (MIT). Regenerate after changing tools/icon-map.json.');
out.push(`// ${names.length} icons x ${WEIGHTS.length} weights.`);
out.push('');
out.push("export type IconWeight = " + WEIGHTS.map(w => `'${w}'`).join(' | ') + ';');
out.push('export type IconName =');
out.push(names.map(n => `    | '${n}'`).join('\n') + ';');
out.push('');
out.push('export const ICONS: Record<IconWeight, Record<IconName, string>> = {');

for (const weight of WEIGHTS) {
    out.push(`    ${weight}: {`);
    for (const name of names) {
        const file = resolve(ROOT, `node_modules/@phosphor-icons/core/assets/${weight}/${name}${weight === 'regular' ? '' : '-' + weight}.svg`);
        let svg;
        try {
            svg = readFileSync(file, 'utf8');
        } catch {
            // Phosphor's regular weight has no suffix; every other weight does. If a name is
            // missing in a non-regular weight, fall back rather than emitting a hole — a missing
            // bold variant should render the regular one, not nothing.
            svg = readFileSync(resolve(ROOT, `node_modules/@phosphor-icons/core/assets/regular/${name}.svg`), 'utf8');
        }
        const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
        out.push(`        '${name}': ${JSON.stringify(inner)},`);
    }
    out.push('    },');
}
out.push('};');
out.push('');

writeFileSync(resolve(ROOT, 'src/app/shared/icon-data.generated.ts'), out.join('\n'));
console.log(`wrote ${names.length} icons x ${WEIGHTS.length} weights`);
